## Николай Сауткин
https://hh.ru/resume/3ea9dfd0ff0b5397660039ed1f6f67614d6661

#### SQL
Таблица history находится в прикреплённом файле test.db (SQLite)
#### history
 - issue_key – уникальный ключ задачи
 - status – статус задачи
 - minutes_in_status – количество минут, которое задача находилась в статусе
 - previous_status – предыдущий статус задачи
 - started_at – время создания статуса задачи, unix миллисекунды 
 - ended_at – время перехода задачи в другой статус, unix миллисекунды

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import sql
engine = create_engine('sqlite:///test.db')

### SQL 1
Напишите запрос, который выведет, сколько времени в среднем задачи каждой группы находятся в статусе “Open”.

Условия:

Под группой подразумевается первый символ в ключе задачи. Например, для ключа “C-40460” группой будет “C”.

Задача может переходить в один и тот же статус несколько раз.

Переведите время в часы с округлением до двух знаков после запятой.

In [2]:
connection = engine.connect()
sql_query = sql.text(
"""
SELECT
    substr(issue_key, 1, 1) as group_,
    round(avg(minutes_in_status) / 60, 2) as average_open
FROM history
WHERE status = 'Open'
GROUP BY group_
""")

df = pd.read_sql(sql_query, connection)
connection.close()

df

  group_  average_open
0      A        153.69
1      B        191.94
2      C        308.20
3      D        570.12
4      E        405.62

### SQL 2 

Напишите запрос, который выведет ключ задачи, последний статус и его время создания для задач, которые открыты на данный момент времени.

Условия:

Открытыми считаются задачи, у которых последний статус в момент времени не “Closed” и не “Resolved”.

Задача может переходить в один и тот же статус несколько раз.

Оформите запрос таким образом, чтобы, изменив дату, его можно было использовать для поиска открытых задач в любой момент времени в прошлом.

Переведите время в текстовое представление.

In [3]:
connection = engine.connect()
sql_query = sql.text(
"""
SELECT
    a.issue_key,
    b.status,
    DATETIME(a.started_at / 1000, 'unixepoch') as started_datetime
FROM
    (SELECT
        issue_key,
        max(started_at) as started_at
    FROM history
    WHERE started_at <= UNIXEPOCH('2023-02-03 12:00:00') * 1000
    GROUP BY issue_key
    ) as a
LEFT JOIN 
    (SELECT * FROM history) as b
    ON a.issue_key = b.issue_key
    AND a.started_at = b.started_at
WHERE status not in ('Closed', 'Resolved')
""")

df = pd.read_sql(sql_query, connection)
connection.close()

df

   issue_key                   status     started_datetime
0    A-31053                     Open  2020-10-21 15:08:13
1    A-32133                     Open  2021-04-29 09:55:29
2    A-37761                   In Owl  2022-12-28 08:18:46
3    A-42030                     Open  2022-09-01 15:04:15
4    A-44107                   In Owl  2022-12-26 18:31:23
5    A-44901                   In Owl  2022-12-27 12:11:12
6    A-44916                  Blocked  2022-09-15 09:17:04
7    A-47808                 Reopened  2022-10-31 08:54:08
8    A-49140                 Reopened  2022-12-29 11:03:37
9    A-49829                In Review  2022-10-20 10:13:04
10   A-50359                   In Owl  2022-11-15 06:51:48
11   A-50422               In Testing  2022-11-01 11:56:49
12   A-51466  Waiting for integration  2022-11-14 12:42:43
13   A-52727  Waiting for integration  2022-12-27 12:11:11
14   A-52884                  Blocked  2022-11-28 15:12:43
15   A-53409  Waiting for integration  2022-12-12 15:08:39
16   A-53444                     Open  2022-12-07 09:19:27
17   A-53602  Waiting for integration  2022-12-26 13:03:29
18   A-53676  Waiting for integration  2022-12-26 18:31:22
19   A-54115                     Open  2022-12-20 17:57:23
20   A-54133  Waiting for integration  2022-12-26 14:47:37
21   A-54460              In Progress  2022-12-28 13:08:03
22   A-54472                  Blocked  2023-01-09 13:10:12
23   A-54508              In Progress  2022-12-29 10:35:40
24   A-54511              In Progress  2022-12-29 11:35:16
25   A-54645              In Progress  2023-01-10 07:11:23
26    B-4645                     Open  2022-12-08 16:18:44
27       C-1              In Progress  2019-06-04 14:38:59
28   C-20610                 Reopened  2021-11-23 14:44:58
29   C-21435                     Open  2022-04-07 12:15:34
30   C-39466              In Progress  2022-11-16 09:50:38
31   C-40460               In Testing  2022-12-07 08:25:32
32   C-42088               In Testing  2022-12-28 15:34:50
33    D-4951                   In Owl  2022-12-21 10:17:40
34    D-5051                     Open  2022-03-14 09:30:51
35    D-5310                     Open  2022-04-18 07:48:07
36    D-5518              In Progress  2022-10-27 11:40:53
37    D-6832               In Testing  2022-12-09 10:11:28
38       D-8                     Open  2019-12-27 11:34:47
39   E-66462               In Testing  2022-12-28 13:08:04